name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true
  CONFIGURATION: Release

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Install Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - uses: xt0rted/markdownlint-problem-matcher@v3.0.0

      - run: npm ci

      - run: npm test

  build:
    runs-on: windows-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1

      - name: Build version suffix (main)
        if: github.event_name == 'push'
        run: echo "VERSION_SUFFIX=beta.${{ github.run_number }}" >> $GITHUB_ENV
        shell: bash

      - name: Build version suffix (pr)
        if: github.event_name == 'pull_request'
        run: echo "VERSION_SUFFIX=alpha.${{ github.event.number }}" >> $GITHUB_ENV
        shell: bash

      - name: Set up .NET
        uses: xt0rted/setup-dotnet@v1.5.0
        with:
          source-url: https://nuget.pkg.github.com/xt0rted/index.json
          nuget_auth_token: ${{ secrets.GITHUB_TOKEN }}

      - run: dotnet tool restore

      - run: dotnet r build

      - run: dotnet r test -- --no-build --logger GitHubActions

      - run: dotnet r pack -- --version-suffix ${{ env.VERSION_SUFFIX }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: nupkg
          path: ./artifacts/*.nupkg

  release:
    if: github.event_name == 'push'

    needs:
      - build
      - lint-markdown

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Download nupkg
        uses: actions/download-artifact@v4.1.4
        with:
          name: nupkg

      - name: Publish to GPR
        run: |
          dotnet nuget push "./*.nupkg" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}
